type Collection {
  id: Int!
  name: String!
  slug: String!
  createdAt: String!
  documents: [Document!]!
}

type Document {
  id: Int!
  title: String!
  content: String!
  tags: [String!]!
  isArchived: Boolean!
  createdAt: String!
  collectionId: Int!
}

type Query {
  collections: [Collection!]!

  collection(id: Int!): Collection

  documents(
    collectionId: Int
    search: String
    isArchived: Boolean
    take: Int
    cursor: Int
  ): [Document!]!
}

type Mutation {
  createCollection(name: String!, slug: String!): Collection!

  createDocument(
    title: String!
    content: String!
    tags: [String!]
    collectionId: Int!
  ): Document!

  updateDocument(
    id: Int!
    title: String
    content: String
    tags: [String!]
    isArchived: Boolean
  ): Document!

  deleteDocument(id: Int!): Document!

  moveDocument(id: Int!, collectionId: Int!): Document!
}